version: "3.9"
services:
  backend:
    build:
      context: ./apps/backend
    image: coffeeee-backend:latest
    environment:
      - PORT=8080
      - HOST=0.0.0.0
      - ENV=production
      - DATABASE_URL=/data/coffee.db
      - DATABASE_MIGRATIONS_PATH=/migrations
      - JWT_SECRET=${JWT_SECRET:-change-me}
      - ALLOWED_ORIGINS=http://localhost:5173,http://frontend
    volumes:
      - backend-data:/data
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./apps/frontend
    image: coffeeee-frontend:latest
    environment:
      - VITE_API_BASE_URL=http://backend:8080
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  backend-data:
