// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"
)

type BrewLog struct {
	ID               int64           `json:"id"`
	UserID           int64           `json:"user_id"`
	CoffeeID         int64           `json:"coffee_id"`
	BrewMethod       string          `json:"brew_method"`
	CoffeeWeight     sql.NullFloat64 `json:"coffee_weight"`
	WaterWeight      sql.NullFloat64 `json:"water_weight"`
	GrindSize        sql.NullString  `json:"grind_size"`
	WaterTemperature sql.NullFloat64 `json:"water_temperature"`
	BrewTime         sql.NullInt64   `json:"brew_time"`
	TastingNotes     sql.NullString  `json:"tasting_notes"`
	Rating           sql.NullInt64   `json:"rating"`
	CreatedAt        time.Time       `json:"created_at"`
}

type Coffee struct {
	UserID      int64          `json:"user_id"`
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	Origin      sql.NullString `json:"origin"`
	Roaster     sql.NullString `json:"roaster"`
	Description sql.NullString `json:"description"`
	PhotoPath   sql.NullString `json:"photo_path"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type User struct {
	ID           int64     `json:"id"`
	Username     string    `json:"username"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	PasswordSalt string    `json:"password_salt"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}
