// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	CreateCoffee(ctx context.Context, arg CreateCoffeeParams) (CreateCoffeeRow, error)
	FindCoffeeByUserAndDetails(ctx context.Context, arg FindCoffeeByUserAndDetailsParams) (int64, error)
	GetCoffeeByID(ctx context.Context, arg GetCoffeeByIDParams) (GetCoffeeByIDRow, error)
	GetCoffeeByIDOnly(ctx context.Context, id int64) (GetCoffeeByIDOnlyRow, error)
	ListCoffeesForUser(ctx context.Context, userID int64) ([]ListCoffeesForUserRow, error)
	UpdateCoffeePhotoPath(ctx context.Context, arg UpdateCoffeePhotoPathParams) error
}

var _ Querier = (*Queries)(nil)
